
# Card lists. 
##    Most cards used come from Cards Against Humanity, licenced under
##    a Creative Commons Attribution - Noncommercial - Share Alike 
##    license. <http://cardsagainsthumanity.com/>

BLACKCARDS = [
['Alternative medicine is now embracing the curative powers of ____.',0,1],
['And the Academy Award for ____ goes to ____.',1,2],
['Betcha can\'t have just one!',0,1],
['BILLY MAYS HERE FOR ____.',0,1],
['But before I kill you Mr. Bond, I must show you ____.',0,1],
['Due to a PR fiasco, Wal*Mart no longer offers ____.',0,1],
['During Picasso\'s often-overlooked "Brown Period", he produced hundreds of paintings of ____.',0,1],
['During sex, I like to think about ____.',0,1],
['For my next trick, I will pull ____ out of ____.',1,2],
['How am I maintaining my relationship status?',0,1],
['How do I shot web?',0,1],
['How I mine for fish?',0,1],
['How is babby formed?',0,1],
['I accidentally a whole ____.',0,1],
['I drink to forget ____.',0,1],
['I wish I hadn\'t lost the instruction manual for ____.',0,1],
['In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.',0,1],
['Instead of coal, Santa now gives the bad children ____.',0,1],
['IT\'S A TRAP!',0,1],
['Life was difficult for cavemen before ____.',0,1],
['Lifetime Network presents ____, the story of ____.',1,2],
['Major League Baseball has banned ____ for giving players an unfair advantage.',0,1],
['Sorry everyone, I just ____.',0,1],
['Studies show that lab rats navigate mazes 50 percent faster after being exposed to ____.',0,1],
['That\'s right, I killed ____. How, you ask? ____',1,2],
['The class field trip was completely ruined by ____.',0,1],
['The U.S. has begun air-dropping ____ to the children of Afghanistan.',0,1],
['War! What is it good for?',0,1],
['What are my parents hiding from me?',0,1],
['What did I bring back from Mexico?',0,1],
['What did Vin Diesel eat for dinner?',0,1],
['What do old people smell like?',0,1],
['What does Dick Cheney prefer?',0,1],
['What don\'t you want to find in your Chinese food?',0,1],
['What gets better with age?',0,1],
['What gives me uncontrollable gas?',0,1],
['What helps Obama unwind?',0,1],
['What is Batman\'s guilty pleasure',0,1],
['What will always get you laid?',0,1],
['What will I bring back in time to convince people I am a powerful wizard?',0,1],
['What would grandma find disturbing, yet oddly charming?',0,1],
['What\'s a girl\'s best friend?',0,1],
['What\'s my anti-drug?',0,1],
['What\'s my secret power?',0,1],
['What\'s that smell?',0,1],
['What\'s that sound?',0,1],
['What\'s the crustiest?',0,1],
['What\'s the most emo?',0,1],
['What\'s the next happymeal toy?',0,1],
['What\'s the next superhero/sidekick duo?',1,2],
['What\'s there a ton of in heaven?',0,1],
['When I am a billionaire, I shall erect a 50-foot statue to commemorate ____.',0,1],
['When I am President of the United States, I will create the Department of ____.',0,1],
['When I was tripping on acid, ____ turned into ____.',1,2],
['When I\'m in prison, I\'ll have ____ smuggled in.',0,1],
['White people like ____.',0,1],
['Who let the dogs out?',0,1],
['Who stole the cookies from the cookie jar?',0,1],
['Why am I sticky?',0,1],
['Why can\'t I sleep at night?',0,1],
['____. High five, bro.',0,1],
# Best card.
['____ / ____ / ____',2,3],
['____ / ____ / ____',2,3],
['____: good to the last drop.',0,1],
['____: kid-tested, mother-approved.',0,1],
['____? There\'s an app for that.',0,1]
]

WHITECARDS = [
'"Tweeting"',
# Numbers mess up colors. Recommend leaving the space.
' 13375P34K',
' 2 Girls 1 Cup',
' 42',
' 8 oz. of sweet Mexican black-tar heroin',
'A big hoopla about nothing',
'A bleached asshole',
'A can of whoop-ass',
'A cartoon camel enjoying the smooth refreshing taste of a cigarette',
'A clandestine butt scratch',
'A disappointing birthday party',
'A falcon with a cap on its head',
'A fetus',
'A good sniff',
'A GrandeSugarFreeIcedSoyCaramelMacchiato',
'A hot mess',
'A LAN party',
'A lifetime of sadness',
'A look-see',
'A mating display',
'A micropenis',
'A middle-aged man on roller skates',
'A mime having a stroke',
'A monkey smoking a cigar',
'A murder most foul',
'A neglected Tamagotchi',
'A really cool hat',
'A robust mongoloid',
'A sad handjob',
'A sassy black nurse',
'A sea of troubles',
'A snapping turtle biting the tip of your penis',
'A stray pube',
'A Super Soaker full of cat pee',
'A thermonuclear detonation',
'A vibrator',
'A wheelchair death race',
'A windmill full of corpses',
'A wisecracking terrorist',
'A zesty breakfast burrito',
'Aaron Burr',
'Abstinence',
'Accidentally in your base',
'Active listening',
'Adderall',
'Adult Friend Finder',
'Ageism',
'Agriculture',
'AIDS',
'Alcoholism',
'All-you-can-eat shrimp for $4.99',
'Altar boys',
'America',
'American Gladiators',
'Amputees',
'An asymmetric boob job',
'An erection that lasts longer than four hours',
'An ice-pick lobotomy',
'An M. Night Shyamalan plot twist',
'An Oedipus complex',
'Anal beads',
'Androgyny',
'Another god-damn vampire movie',
'Arnold Schwarzenegger',
'Asians who aren\'t good at math',
'Assless chaps',
'Attitude',
'Auschwitz',
'Autocannibalism',
'Axe Body Spray',
'Balls',
'Bananas in pyjamas',
'Barack Obama',
'BATMAN!!',
'Bees?',
'Being a dick to children',
'Being fabulous',
'Being on fire',
'Being rich',
'Bestiality',
'Bill Nye the Science Guy',
'Bingeing and purging',
'Bitches',
'Black people',
'Blue Ice',
'Bond, James Bond',
'Bono',
'Boobs',
'Booby-trapping your home to foil burglars',
'Britney Spears at 65',
'Cameltoe',
'Canned tuna with extra dolphin',
'Cards Against Humanity',
'Catapults',
'Centaurs',
'Chainsaws for hands',
'Cheating in the Special Olympics',
'Child abuse',
'Child beauty pageants',
'Children on leashes',
'Chivalry',
'Christopher Walken',
'Civilian casualties',
'Coat-hanger abortions',
'Cockfests',
'Cockfights',
'Concealing a boner',
'Copping a feel',
'Count Chocula',
'Creed',
'CRUISE CONTROL FOR COOL',
'Crumpets with the Queen',
'CSI',
'Cuddling',
'Dance of the Sugar Plum Fairies',
'Darth Vader',
'Date rape',
'Dave Matthews Band',
'Dead babies',
'Dead parents',
'Dead parrots',
'Dental dams',
'Dick Cheney',
'Dick fingers',
'Doing the right thing',
'Doin\' it in the butt',
'Domino\'s Oreo Dessert Pizza',
'Douchebag on an iPhone',
'Dr. Evil',
'Dr. Martin Luther King, Jr.',
'Drinking alone',
'Drum circles',
'Dry heaving',
'Dwarf tossing',
'Dying of dysentery',
'Dying',
'Eastern European Turbo-Folk music',
'Eating all the cookies before the AIDS bake-sale',
'Eating Jesus',
'Eating too much of a lamp',
'Edible underpants',
'Edward Scissor-Hands',
'Elderly Japanese men',
'Emotions',
'Estrogen',
'Ethnic cleansing',
'Exchanging pleasantries',
'Existentialists',
'Faith healing',
'Falcon Punch!',
'Fancy Feast',
'Farting and walking away',
'Fear itself',
'Feeding Rosie O\'Donnell',
'Fiery poops',
'Figgy pudding',
'Fingering',
'Five-dollar footlongs',
'Flash flooding',
'Flavo(u)red condoms',
'Flightless birds',
'Foreskin',
'Forgetting the Alamo',
'Four Loko',
'Free samples',
'Friction',
'Friendly fire',
'Friends who eat all your snacks',
'Friends with benefits',
'Frolicking',
'Front butt',
'Furries',
'Garden-variety internet trolls',
'Gary Coleman',
'Geese',
'Genghis Khan',
'Genital piercings',
'German dungeon porn',
'Getting drunk on mouthwash',
'Getting so angry that you pop a boner',
'Ghandi',
'Ghosts',
'Girls who shouldn\'t go wild',
'Giving 110 percent',
'Glenn Beck',
'Global Warming',
'Gloryholes',
'Go-gurt',
'Goats eating cans',
'Goblins',
'Golden showers',
'Grandma',
'Grave robbing',
'Guys/girls who don\'t call',
'Half-assed foreplay',
'Harry Potter erotica',
'Have some more kugel',
'Heath Ledger',
'Her Royal Highness, Queen Elizabeth II.',
'Historically black colleges',
'Home video of Oprah sobbing into a Lean Cuisine',
'Homeless people',
'Hot people',
'Hot pockets',
'Hulk Hogan',
'Hunting accidents',
'Hurricane Katrina',
'I am doing kegels right now',
'Impotence',
'Improvised explosive devices',
'Inappropriate yodeling',
'Incest',
'Intelligent Design',
'Iron Man',
'Irritable Bowel Syndrome',
'Italians',
'I\'m friends with your dad on Facebook',
'Jerking off into a pool of children\'s tears',
'Jew-fros',
'Jewish fraternities',
'John Wilkes Booth',
'Judge Judy',
'Justin Bieber',
'Kamikaze pilots',
'Kanye West',
'Keanu Reeves',
'Keeping Christ in Christmas',
'Keg stands',
'Kibbles \'n Bits',
'Kids with ass cancer',
'Kim Jong-Il',
'Lactation',
'Lance Armstrong\'s missing testicle',
'Land mines',
'Leaving an awkward voicemail',
'Leprosy',
'Licking things to claim them as your own',
'Lockjaw',
'Loose lips',
'Lumberjack fantasies',
'Lunchables',
'Mad Cow Disease',
'Magnets',
'Making a pouty face',
'Making sex at her',
'Man meat',
'Martha Stewart (post prison)',
'Masturbation',
'Mathletes',
'Men',
'Menstruation',
'Michael Jackson',
'Mouth herpes',
'Mr. Clean, right behind you',
'Muhammad (Praise Be Unto Him)',
'Multiple stab wounds',
'Mutually-assured destruction',
'Muzzy!',
'My collection of high-tech sex toys',
'My genitals',
'My relationship status',
'My sex life',
'My soul',
'Natalie Portman',
'Natural selection',
'Nazis',
'Necrophilia',
'New Age music',
'Nip Slips',
'Nipple blades',
'Nocturnal emissions',
'Not reciprocating oral sex',
'Obesity',
'Obscure internet acronyms',
'Old-people smell',
'Oompa Loompas',
'Overcompensation',
'Oversized lollipops',
'Pabst Blue Ribbon',
'Pac-Man uncontrollably guzzling cum',
'Panda sex',
'Paris Hilton',
'Parting the Red Sea',
'Party poppers',
'Passable transvestites',
'Passing a kidney stone',
'Passive-agression',
'PCP',
'Peanut Butter Jelly Time',
'Pedophiles',
'Peeing a little bit',
'Penis envy',
'People who smell their own socks',
'Picking up girls at the abortion clinic',
'Pixelated bukkake',
'Pooping back and forth. Forever.',
'Pooping in the soup',
'Poor people',
'Poorly-timed Holocaust jokes',
'Popped collars',
'Prancing',
'Praying the gay away, Westboro Baptist Church style',
'Pre-teens',
'Pterodactyl eggs',
'Puberty',
'Pulling out',
'Puppies!',
'Queefing',
'Racially-biased SAT questions',
'Racism',
'Raptor attacks',
'Re-gifting',
'Repression',
'Rick Astley',
'Ring Pops',
'Rip Torn drop-kicking anti-Semitic lesbians',
'Road head',
'Robbing a sperm bank',
'Robert Downey, Jr.',
'Robin',
'Ronald Reagan',
'Rule 34',
'Same-sex ice dancing',
'Sarah Palin',
'Saxophone solos',
'Scalping',
'Science',
'Scientology',
'Scrubbing under the folds',
'Sean Connery',
'Sean Penn',
'Sedation',
'Seduction',
'Seppuku',
'Serfdom',
'Sexual tension',
'Shaquille O\'Neal\'s acting career',
'Shorties and blunts',
'Showing up to an orgy for the food',
'Sipping artificial popcorn butter',
'Skeletor',
'Smallpox blankets',
'Smegma',
'Sniffing glue',
'Soiling oneself',
'Spectacular abs',
'Sperm whales',
'Spontaneous human combustion',
'Stephen hawking talking dirty',
'Steve Irwin',
'Stifling a giggle at the mention of Hutus and Tutsis',
'Stranger danger',
'Substitute teachers',
'Sucking some dicks not to get drafted',
'Sunshine and rainbows',
'Surprise sex!',
'Sweet, sweet vengence',
'Swooping',
'Taking off your shirt',
'Tasteful sideboob',
'Teaching a robot to love',
'Team-building exercises',
'Teh Interwebz',
'Tentacle porn',
'Testicular torsion',
'That one gay Teletubby',
'That thing I sent ya',
'That thing that electrocuted your abs',
'The Amish',
'The Big Bang',
'The blood of Christ',
'The Chinese gymnastic team',
'The clitoris',
'The drama club',
'The Fish Slapping Dance',
'The folly of man',
'The gays',
'The Hamburglar',
'The hard-working Mexican',
'The heart of a child',
'The Holy Bible',
'The homosexual \'agenda\'',
'The Hustle',
'The Jews',
'The KKK',
'The Kool-aid man',
'The Ministry of Silly Walks',
'The placenta',
'The plot of a Michael Bay movie',
'The Pope',
'The profoundly handicapped',
'The Rise and Fall of the Roman Empire',
'The South',
'The Superdome',
'The taint; the grundle; the fleshy fun-bridge',
'The Thong Song',
'The Three-Fifths Compromise',
'The token minority',
'The Trail of Tears',
'The Underground Railroad',
'The Virginia Tech Massacre',
'The World of Warcraft',
'Thinly-veiled insanity',
'Third base',
'This answer is post-modern',
'Those times when you get sand in your vagina',
'Throwing a hotdog down a hallway',
'Tickle Me Elmo',
'Tiger Woods',
'Tom Cruise',
'Toni Morrison\'s vagina',
'Too much hair gel',
'Touching myself',
'Transvestites',
'Twilight',
'Twinkies',
'Two midgets shitting into a bucket',
'Uppercuts',
'Viagra',
'Vigorous jazz hands',
'Vikings',
'Waiting \'til marriage',
'Waking up half-naked in a Denny\'s parking lot',
'Waterboarding',
'Wearing underwear inside out to avoid doing laundry',
'When you fart and a little bit comes out',
'White people',
'Will Smith',
'William Shatner',
'Winking at old people',
'Wiping her butt',
'Women in yogurt commercials',
'Women',
'Women\'s suffrage',
'World peace',
'Yeast',
'Zyklon B',
'\'Me\' time',
'\\o/',
]